# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu


# navigation menu
menu:
  - name: Recent
    slug: recent
    url: /recent
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: Gallery
    slug: gallery
    url: /gallery
  - name: Timeline
    slug: timeline
    url: /timeline
  - name: Project
    slug: project
    url: /project
  # - name: Tagcloud
  #   slug: tagcloud
  #   url: /tagcloud
  # - name: Link
  #   slug: link
  #   url: /link
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - categories
  - tagcloud
  - music
  - links

music_id: 27461822


# links info
links:
  - name: Zhejiang Univ
    url: http://www.zju.edu.cn
  - name: CKC 
    url: http://ckc.zju.edu.cn/

# Less
less:
  compress: true

social:
- slug: github
  url: https://github.com/96486d9b
- slug: facebook
  url: https://www.facebook.com/profile.php?id=100032502468035
- slug: instagram
  url: https://www.instagram.com/96486d9b
- slug: twitter
  url: https://twitter.com/bryce04343695
- slug: rss
  url: /atom.xml

valine:
  enable: false
  appId: 
  appKey: 

reading:
  enable: true
  entry_excerpt: 200
  timeline_excerpt: 50
